# Phyloseq-working

## 10.17.26 | tidy metadata

### Setting up R/phyloseq with conda environment in unity

Add phyloseq to `dada2-env` in terminal
```
conda activate dada2-env
conda install -c bionconda bioconda-phyloseq
```

### Metadata tidying

In [1]:
# Load packages
suppressPackageStartupMessages({
    library(phyloseq)
    library(Biostrings)
    library(tidyverse)
})

In [2]:
# Read 16S processing tracker csv
meta16S <- read.csv("/project/pi_sarah_gignouxwolfsohn_uml_edu/jade/ORCC_16S/metadata/16S_tracker.csv")
dim(meta16S)
head(meta16S)

[1] 283  30

  Original_order Sample_name            Phase Tissue Concentration DNA_dilution
1  2             2024_Both05_Warm03_O33 2     gut    53.0          0.1
2  4             2024_Both06_Hyp06_O72  2     gut    53.8          0.1
3  8             2024_Cont02_Warm02_W15 2     gut    29.2          0.1
4 10             2024_Both03_Warm01_O6  2     gut    77.8          0.1
5 12             2024_Both03_Warm04_O41 2     gut    86.9          0.1
6 14             2024_Both04_Warm02_O19 2     gut    38.7          0.1
  X16S_date X16S_tube_number X16S_adapters X16S_tray ⋯ Pooled_notes
1 12/15/25  2                3N            1         ⋯ <15uL
2 12/15/25  4                3N            1         ⋯
3 12/15/25  8                3N            1         ⋯
4 12/16/25  2                3N            1         ⋯ <15uL
5 12/16/25  4                3N            1         ⋯
6 12/16/25  6                3N            1         ⋯
  Index_primers Index_date Index_volume Clean_date Clean_date_2 Gel_extraction
1 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
2 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
3 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
4 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
5 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
6 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
  Final_concentration X25ng Notes
1  6.10               4.10
2  8.88               2.82
3  6.64               3.77
4 10.00               2.50
5  9.86               2.54
6  7.52               3.32

In [3]:
# Tidy data
meta16S <- meta16S %>% 
                mutate(Original_order = NULL) %>%
                separate(Sample_name,  into = c("Year", "Phase_1_treat", "Phase_2_treat", "Tag"), sep = "_", remove = FALSE) %>%
                rename(Date = X16S_date) %>%
                mutate(Date = as.Date(Date, format = "%m/%d/%y")) %>%
                rename(Adapters = X16S_adapters) %>%
                mutate(Index_date = as.Date(Index_date, format = "%m/%d/%y"))
head(meta16S)

Warning message:
“Expected 4 pieces. Missing pieces filled with `NA` in 7 rows [239, 240, 243,
247, 280, 282, 283].”

  Sample_name            Year Phase_1_treat Phase_2_treat Tag Phase Tissue
1 2024_Both05_Warm03_O33 2024 Both05        Warm03        O33 2     gut
2 2024_Both06_Hyp06_O72  2024 Both06        Hyp06         O72 2     gut
3 2024_Cont02_Warm02_W15 2024 Cont02        Warm02        W15 2     gut
4 2024_Both03_Warm01_O6  2024 Both03        Warm01        O6  2     gut
5 2024_Both03_Warm04_O41 2024 Both03        Warm04        O41 2     gut
6 2024_Both04_Warm02_O19 2024 Both04        Warm02        O19 2     gut
  Concentration DNA_dilution Date       ⋯ Pooled_notes Index_primers Index_date
1 53.0          0.1          2025-12-15 ⋯ <15uL        BFi-14        2026-06-26
2 53.8          0.1          2025-12-15 ⋯              BFi-14        2026-06-26
3 29.2          0.1          2025-12-15 ⋯              BFi-14        2026-06-26
4 77.8          0.1          2025-12-16 ⋯ <15uL        BFi-14        2026-06-26
5 86.9          0.1          2025-12-16 ⋯              BFi-14        2026-06-26
6 38.7          0.1          2025-12-16 ⋯              BFi-14        2026-06-26
  Index_volume Clean_date Clean_date_2 Gel_extraction Final_concentration X25ng
1 2            6/30/26    7/1/26       NA              6.10               4.10
2 2            6/30/26    7/1/26       NA              8.88               2.82
3 2            6/30/26    7/1/26       NA              6.64               3.77
4 2            6/30/26    7/1/26       NA             10.00               2.50
5 2            6/30/26    7/1/26       NA              9.86               2.54
6 2            6/30/26    7/1/26       NA              7.52               3.32
  Notes
1
2
3
4
5
6

In [4]:
# Check warning message
meta16S[239:247,]
meta16S[280:283,]
# Missing pieces are control samples

    Sample_name             Year     Phase_1_treat Phase_2_treat Tag Phase
239 Pooled_negative_rack1   Pooled   negative      rack1         NA  NA
240 Pooled_negative_rack2   Pooled   negative      rack2         NA  NA
241 2024_Hyp01_Null_B08     2024     Hyp01         Null          B08  1
242 2024_Hyp05_Null_B35     2024     Hyp05         Null          B35  1
243 Pooled_negative_rack3   Pooled   negative      rack3         NA  NA
244 2024_Warm02_Null_G15    2024     Warm02        Null          G15  1
245 Pooled_negative_rack3_2 Pooled   negative      rack3         2   NA
246 2024_Warm04_Null_G27    2024     Warm04        Null          G27  1
247 negative_control        negative control       NA            NA  NA
    Tissue Concentration DNA_dilution Date       ⋯ Pooled_notes
239 NA         NA         NA          <NA>       ⋯
240 NA         NA         NA          <NA>       ⋯
241 gill    1.730        2.0          2026-04-15 ⋯
242 gill    5.800        5.0          2026-04-15 ⋯
243 NA         NA         NA          <NA>       ⋯
244 gill    0.196        5.0          2026-04-15 ⋯
245 NA         NA         NA          <NA>       ⋯
246 gill    6.300        2.0          2026-07-31 ⋯ Redo - clean before indexing
247 NA     -1.900        0.1          2026-04-15 ⋯
    Index_primers Index_date Index_volume Clean_date Clean_date_2
239 BFi-14        2026-06-26 1            6/30/26    7/1/26
240 BFi-15        2026-07-03 1            7/3/26     NA
241 BFi-13        2026-07-06 1            7/6/26     NA
242 BFi-13        2026-07-06 1            7/6/26     NA
243 BFi-13        2026-07-06 1            7/6/26     NA
244 BFi-13        2026-07-06 1            7/6/26     NA
245 BFi-13        2026-07-08 1            7/10/26    NA
246 BFi-13        2026-07-31 2            8/4/26     NA
247 BFi-13        2026-07-06 1            7/6/26     NA
    Gel_extraction Final_concentration X25ng
239 NA              1.14               3.00
240 NA              5.02               3.00
241 NA             11.07               2.26
242 NA              7.53               3.32
243 NA              1.25               3.00
244 NA              8.27               3.02
245 NA              2.20               3.00
246 NA              3.76               6.65
247 NA              3.64               3.00
    Notes
239 Rack 1 negative
240 Rack 2 negative; primer dimer that didn't get cleaned
241 Diluted final sample 1:3
242 Diluted final sample 1:3
243 Rack 3 negative
244 Diluted final sample 1:3
245 Rack 3 negative
246
247

    Sample_name             Year     Phase_1_treat Phase_2_treat Tag Phase
280 Positive_control        Positive control       NA            NA  NA
281 Pooled_negative_rack3_3 Pooled   negative      rack3         3   NA
282                                  NA            NA            NA  NA
283                                  NA            NA            NA  NA
    Tissue Concentration DNA_dilution Date       ⋯ Pooled_notes
280 NA     NA            0.001        2026-07-31 ⋯ Clean before indexing
281 NA     NA               NA        <NA>       ⋯ Clean before indexing
282        NA               NA        <NA>       ⋯
283        NA               NA        <NA>       ⋯
    Index_primers Index_date Index_volume Clean_date Clean_date_2
280 BFi-13        2026-07-31  2           NA         NA
281 BFi-13        2026-07-31  2           8/4/26     NA
282               <NA>       NA
283               <NA>       NA
    Gel_extraction Final_concentration X25ng Notes
280 8/4/26         5.50                4.55
281 NA             0.26                3.00  Rack 3 negative
282                  NA                  NA
283                  NA                  NA

In [5]:
# Remove empty rows 282, 283
meta16S <- meta16S[-282:-283,]
tail(meta16S)

    Sample_name             Year     Phase_1_treat Phase_2_treat Tag Phase
276 2024_Warm05_Cont04_G45  2024     Warm05        Cont04        G45  2
277 2024_Both03_Warm04_O41  2024     Both03        Warm04        O41  2
278 2024_Cont06_Null_W42    2024     Cont06        Null          W42  1
279 2024_Hyp02_Hyp01_B3     2024     Hyp02         Hyp01         B3   2
280 Positive_control        Positive control       NA            NA  NA
281 Pooled_negative_rack3_3 Pooled   negative      rack3         3   NA
    Tissue Concentration DNA_dilution Date       ⋯ Pooled_notes
276 gill   34.800        2.000        2026-07-31 ⋯ Redo - clean before indexing
277 gill   43.500        1.000        2026-04-24 ⋯
278 gill    0.676        2.000        2026-07-31 ⋯ Redo - clean before indexing
279 gut    40.800        0.100        2026-07-31 ⋯ Redo - clean before indexing
280 NA         NA        0.001        2026-07-31 ⋯ Clean before indexing
281 NA         NA           NA        <NA>       ⋯ Clean before indexing
    Index_primers Index_date Index_volume Clean_date Clean_date_2
276 BFi-13        2026-07-31 2            NA         NA
277 BFi-13        2026-07-22 2            NA         NA
278 BFi-13        2026-07-31 2            8/4/26     NA
279 BFi-13        2026-07-31 2            NA         NA
280 BFi-13        2026-07-31 2            NA         NA
281 BFi-13        2026-07-31 2            8/4/26     NA
    Gel_extraction Final_concentration X25ng
276 8/4/26         4.16                 6.01
277 7/24/26        4.90                 5.10
278 NA             2.34                10.68
279 8/4/26         2.34                10.68
280 8/4/26         5.50                 4.55
281 NA             0.26                 3.00
    Notes
276
277
278
279 Re-index with rack 3 (was rack 1, tube 43)
280
281 Rack 3 negative

In [7]:
# Save tided csv
write.csv(meta16S, "/project/pi_sarah_gignouxwolfsohn_uml_edu/jade/ORCC_16S/metadata/metadata_samples.csv")

## 10.18.26 | phyloseq on decipher taxonomy

In [9]:
# Load additional packages
suppressPackageStartupMessages({
    library(data.table)
})

In [11]:
# Load ASV table using fread because csv is large
seqtab.nochim <- fread("/scratch4/workspace/jade_fiorilla_student_uml_edu-rawseqorcc/dada2/ASV_nochim.csv")
seqtab.nochim <- as.matrix(seqtab.nochim)
storage.mode(seqtab.nochim) <- "numeric"
# -- AI, turn CSV into format required by dada2
# -- Save as an RDS object next time rather than a csv and use lines below

# Load RDS from ASV-table.r
# seqtab.nochim <- readRDS("/scratch4/workspace/jade_fiorilla_student_uml_edu-rawseqorcc/dada2/ASV_nochim.rds")

Warning message in storage.mode(seqtab.nochim) <- "numeric":
“NAs introduced by coercion”

In [12]:
head(seqtab.nochim)

     V1
[1,] NA
[2,] NA
[3,] NA
[4,] NA
[5,] NA
[6,] NA
     GAAGGGGGCGAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGTCTAGGTGGTTTTGTTAGTTGGATGTGAAAGCCCTCGGCTCAACCGAGGAATTGCATCCAAAACTGCATTACTAGAGTGTGAAAGGGGAAGGCGGAATTCCAAGTGTAGCGGTGAAATGCGTAGATATTTGGAGGAACACCGGTGGCGAAGGCGGCCTTCTGGTTCAACACTGACACTAAAGCGCGAAGGCTAGGGGAGCGAAC
[1,] 95318
[2,]  5708
[3,]    90
[4,]   120
[5,] 14252
[6,]   647
     GAAGGGGGCAAGCGTTGTTCGGAATTACTGGGCGTAAAGAGTACGTAGGCGGTTAGATTAGTTAGGTGTGAAATCCCGGAGCTCAACTTCGGAGTTGCACTTAATACTGTTTAACTAGAATTCAAGAGGGGAGAGTGGAATTTCCAGTGTAGGGGTGATATCCGTAGATATTGGAAGGAACATCAGAGGCGAAGGCGACTCTCTGGCTTGACATTGACGCTGAGGTACGAAAGCGTGGGTAGCAAAC
[1,] 16481
[2,] 23075
[3,]    13
[4,]   340
[5,] 14382
[6,] 17489
     GGGAGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGCGGTCTTGTAAGTCTGTTGTTAAAGCGTGGAGCTTAACTCCATTTCAGCAATGGAAACTGTAAGACTAGAGTGTGGTAGGGGCAGAGGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAAGAACACCAGTGGCGAAGGCGCTCTGCTGGGCCATAACTGACGCTCATGGACGAAAGCCAGGGGAGCGAAA
[1,]  5974
[2,]  2326
[3,]   188
[4,] 22494
[5,]  2982
[6,]  6615
     GGAGGATGCAAGTGTTATCCGGAATCACTGGGCGTAAAGCGTCTGTAGGTGGTTTAATAAGTCAACTGTTAAATCTTGAGGCTCAACTTCAAAATCGCAGTCGAAACTATTAGACTAGAGTATAGTAGAGGTAAAGGGAATTTCCAGTGGAGCGGTGAAATGCGTAGATATTGGAAAGAACACCGATGGCGAAAGCACTTTACTGGGCTATTACTAACACTCAGAGACGAAAGCTAGGGTAGCAAAT
[1,] 2042
[2,]  907
[3,]   42
[4,] 1514
[5,] 9025
[6,] 4269
     GGGAGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGCGGTCTGTCAAGTCTGCTGTTAAAGCGTGGAGCTTAACTCCATTTCGGCAGTGGAAACTGACAGACTAGAGTGTGGTAGGGGCAGAGGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAAGAACACCAGTGGCGAAGGCGCTCTGCTGGGCCATAACTGACGCTCATGGACGAAAGCCAGGGGAGCGAAA
[1,]  4804
[2,]  1221
[3,]    33
[4,]  5922
[5,]  3907
[6,] 11378
     GGAGGGGGCGAGCGTTATTCGGAATTATTGGGTGTAAAGTGTGCGTAGGCGGCTTAGTAAGTTAATGGTGAAATCCCGGGGCTCAACCCCGGGGCTGCTTTTAGAACTGCTAAGCTGGAGTTGGAAAGAGGATAGCAGAATTCCTAGTGTAGAGGTGAAATTCGTAGATATTAGGAGGAATACCGGAGGCGAAGGCGGCTGTCTGGTTCCATACTGACGCTGAGGCACGAAAGCGTGGGGAGCAAAC
[1,]   440
[2,] 31792
[3,]     0
[4,]  5697
[5,]     0
[6,]  1201
     GGAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGGGTGCGTAGGCGTCTTATTAAGTCAGATGTGAAATCCTGTGGCTCAACCATAGAACTGCATTTGAAACTGGTAAGATAGAGTTCAGAAGGGGCAAGTGGAATTAGTGGTGTAGGGGTAAAATCCGTAGATATCACTAGGAATACCAAAAGCGAAGGCGACTTGCTAGGATGACACTGACGCTGAGGCACGAAAGCGTGGGGAGCAAAC
[1,]   253
[2,]   361
[3,]    43
[4,]    36
[5,] 48679
[6,]  1480
     GTAGGTCCCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGTCCGTAGACGGTTTATTAAGTCTGATGTGAAAGCCACCGGCTCAACCGGTGAAACGCATTAGATACTGGTAAACTAGAGTATGTTAGAGGATAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGCTATCTGGGACATTACTGACGTTGAGGGACGAAAGCGTGGGGAGCGAAC
[1,]  3192
[2,]  7091
[3,]    14
[4,]  3281
[5,]  5038
[6,] 13323
     GAGGATGCAAGTGTTATCCGGAATCACTGGGCGTAAAGCGTCTGTAGGTGGTTTAATAAGTCAACTGTTAAATCTTGATGGCTCAACCTCAAAATCGCAGTCGAAACTATTAGACTAGAGTATAGTAGAGGTAAAGGGAATTTCCAGTGGAGCGGTGAAATGCGTAGATATTGGAAAGAACACCGATGGCGAAAGCACTTTACTGGGCTATTACTAACACTCAGAGACGAAAGCTAGGGTAGCAAA
[1,]   694
[2,]   312
[3,]     0
[4,]   535
[5,] 10685
[6,]  7843
     ⋯
[1,] ⋯
[2,] ⋯
[3,] ⋯
[4,] ⋯
[5,] ⋯
[6,] ⋯
     ATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAA
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     GGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCC
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     CTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAA
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     AAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCCCTTTCGTCTCGCGCGTTTCGGTGATGACGGT
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     CCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTT
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     CGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAA
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     CTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAAT
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     GGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCGAGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGC
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     AGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTACGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATAACCGTATTACCGCCTTTGAGTGAGCTGATACCGCTCGCCGCAGCCGAACGACCGAGCGCAGCGAGTCAGTGAGCGAGGAAGCGGAAGAGCGCCCAATACGCAAACCGCCTCTCCCCGC
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0
     TCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGG
[1,] 0
[2,] 0
[3,] 0
[4,] 0
[5,] 0
[6,] 0

In [ ]:
# Load taxonomy table
taxa <- readRDS("/scratch4/workspace/jade_fiorilla_student_uml_edu-rawseqorcc.decipher_taxa_sp.rds")

In [ ]:
print("hi")

In [ ]:
seqtab.nochim <- readRDS("/scratch4/workspace/jade_fiorilla_student_uml_edu-rawseqorcc/dada2/ASV_nochim.rds")
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)
gender <- substr(subject,1,1)
subject <- substr(subject,2,999)
day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
samdf$When <- "Early"
samdf$When[samdf$Day>100] <- "Late"
rownames(samdf) <- samples.out