# Phyloseq-working

## 10.17.26

### Setting up R/phyloseq with conda environment in unity

Add phyloseq to `dada2-env` in terminal
```
conda activate dada2-env
conda install -c bionconda bioconda-phyloseq
```

### Metadata tidying

In [26]:
# Load packages
library(phyloseq)
library(Biostrings)
library(tidyverse)

In [43]:
# Read metadata tracker csv and subset to only include sample ID information
metaSamples <- read.csv("/project/pi_sarah_gignouxwolfsohn_uml_edu/jade/ORCC_16S/metadata/metadata_tracker.csv") 
tail(metaSamples)
metaSamples <- metaSamples[,3:10] %>% relocate("Sample_Name")
tail(metaSamples)

     Original_order Date_MMDDYYYY Year Phase_1_treat Phase_1_rep Phase_2_treat
1339 1339           8122024       2024 Cont          1           Warm
1340 1340           8122024       2024 Both          1           Warm
1341 1341           8122024       2024 Both          1           Both
1342 1342           8122024       2024 Cont          1           Both
1343 1343           8122024       2024 Warm          1           Both
1344 1344           8122024       2024 Hyp           1           Both
     Phase_2_rep Tag_color Tag_num Sample_Name           phase1_growth
1339 1           W         1       2024_Cont01_Warm01_W1 N
1340 1           O         1       2024_Both01_Warm01_O1 N
1341 1           O         1       2024_Both01_Both01_O1 N
1342 1           W         1       2024_Cont01_Both01_W1 N
1343 1           G         1       2024_Warm01_Both01_G1 N
1344 1           B         1       2024_Hyp01_Both01_B1  N
     phase2_growth nutrients genetic_sample RNAseq_gill
1339 Y             Y         N              N
1340 Y             Y         N              N
1341 Y             Y         Y              N
1342 Y             Y         N              N
1343 Y             Y         N              N
1344 Y             Y         N              N

     Sample_Name           Year Phase_1_treat Phase_1_rep Phase_2_treat
1339 2024_Cont01_Warm01_W1 2024 Cont          1           Warm
1340 2024_Both01_Warm01_O1 2024 Both          1           Warm
1341 2024_Both01_Both01_O1 2024 Both          1           Both
1342 2024_Cont01_Both01_W1 2024 Cont          1           Both
1343 2024_Warm01_Both01_G1 2024 Warm          1           Both
1344 2024_Hyp01_Both01_B1  2024 Hyp           1           Both
     Phase_2_rep Tag_color Tag_num
1339 1           W         1
1340 1           O         1
1341 1           O         1
1342 1           W         1
1343 1           G         1
1344 1           B         1

In [41]:
# Read 16S processing tracker csv
meta16S <- read.csv("/project/pi_sarah_gignouxwolfsohn_uml_edu/jade/ORCC_16S/metadata/16S_tracker.csv")
dim(meta16S)
head(meta16S)

[1] 283  30

  Original_order Sample_name            Phase Tissue Concentration DNA_dilution
1  2             2024_Both05_Warm03_O33 2     gut    53.0          0.1
2  4             2024_Both06_Hyp06_O72  2     gut    53.8          0.1
3  8             2024_Cont02_Warm02_W15 2     gut    29.2          0.1
4 10             2024_Both03_Warm01_O6  2     gut    77.8          0.1
5 12             2024_Both03_Warm04_O41 2     gut    86.9          0.1
6 14             2024_Both04_Warm02_O19 2     gut    38.7          0.1
  X16S_date X16S_tube_number X16S_adapters X16S_tray ⋯ Pooled_notes
1 12/15/25  2                3N            1         ⋯ <15uL
2 12/15/25  4                3N            1         ⋯
3 12/15/25  8                3N            1         ⋯
4 12/16/25  2                3N            1         ⋯ <15uL
5 12/16/25  4                3N            1         ⋯
6 12/16/25  6                3N            1         ⋯
  Index_primers Index_date Index_volume Clean_date Clean_date_2 Gel_extraction
1 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
2 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
3 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
4 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
5 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
6 BFi-14        6/26/26    2            6/30/26    7/1/26       NA
  Final_concentration X25ng Notes
1  6.10               4.10
2  8.88               2.82
3  6.64               3.77
4 10.00               2.50
5  9.86               2.54
6  7.52               3.32

In [64]:
# Tidy df as needed
meta16S$Original_order <- NULL
meta16S$Phase <- NULL
meta16S$X16S_date <- as.Date(meta16S$X16S_date, format='%m/%d/%y')
meta16S$Index_date <- as.Date(meta16S$Index_date, format='%m/%d/%y')
head(meta16S)

  Sample_name            Tissue Concentration DNA_dilution X16S_date
1 2024_Both05_Warm03_O33 gut    53.0          0.1          2025-12-15
2 2024_Both06_Hyp06_O72  gut    53.8          0.1          2025-12-15
3 2024_Cont02_Warm02_W15 gut    29.2          0.1          2025-12-15
4 2024_Both03_Warm01_O6  gut    77.8          0.1          2025-12-16
5 2024_Both03_Warm04_O41 gut    86.9          0.1          2025-12-16
6 2024_Both04_Warm02_O19 gut    38.7          0.1          2025-12-16
  X16S_tube_number X16S_adapters X16S_tray Triplicate Band_brightness ⋯
1 2                3N            1         Y          Present         ⋯
2 4                3N            1         Y          Present         ⋯
3 8                3N            1         Y          Present         ⋯
4 2                3N            1         Y          Present         ⋯
5 4                3N            1         Y          Present         ⋯
6 6                3N            1         Y          Present         ⋯
  Pooled_notes Index_primers Index_date Index_volume Clean_date Clean_date_2
1 <15uL        BFi-14        2026-06-26 2            6/30/26    7/1/26
2              BFi-14        2026-06-26 2            6/30/26    7/1/26
3              BFi-14        2026-06-26 2            6/30/26    7/1/26
4 <15uL        BFi-14        2026-06-26 2            6/30/26    7/1/26
5              BFi-14        2026-06-26 2            6/30/26    7/1/26
6              BFi-14        2026-06-26 2            6/30/26    7/1/26
  Gel_extraction Final_concentration X25ng Notes
1 NA              6.10               4.10
2 NA              8.88               2.82
3 NA              6.64               3.77
4 NA             10.00               2.50
5 NA              9.86               2.54
6 NA              7.52               3.32

In [31]:
# Save csv with just sample information
write.csv(meta, "/project/pi_sarah_gignouxwolfsohn_uml_edu/jade/ORCC_16S/metadata/metadata_samples.csv")

In [ ]:
seqtab.nochim <- readRDS("/scratch4/workspace/jade_fiorilla_student_uml_edu-rawseqorcc/dada2/ASV_nochim.rds")
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)
gender <- substr(subject,1,1)
subject <- substr(subject,2,999)
day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
samdf$When <- "Early"
samdf$When[samdf$Day>100] <- "Late"
rownames(samdf) <- samples.out